### PR TITLE
chore(release): 0.4.0

### PR DESCRIPTION
**Pull request by rupl**
For #394

### CODE REVIEW

**Comment by rupl** [comment]
Whoops we seem to have merged #394 which this was for, so I'll close and we'll get it next time. No biggie.

**Comment by lazysoundsystem** [comment]
@rupl Ah, sorry, I missed this - if you open it again, I can merge it to dev and then to main.

**Comment by lazysoundsystem** [comment]
and that could include https://github.com/UN-OCHA/response-site/pull/396 too.

**Comment by rupl** [comment]
#396 I'd rather test a little bit before deploying but this I can reopen and merge

**Review by lazysoundsystem — APPROVED** [review]

**Pull request merged**
