### PR TITLE
Rwr 157

### PR DESCRIPTION
**Pull request by attiks**

### CODE REVIEW

**Review by lazysoundsystem — APPROVED** [review]
Looks okay, but the tests are failing.

**Comment by attiks** [comment]
Local test

```
XDEBUG_MODE=coverage ./vendor/bin/phpunit --testsuite Existing --verbose html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsRWAssessmentsTest.php 
PHPUnit 9.5.20 #StandWithUkraine

Runtime:       PHP 8.0.17 with Xdebug 3.1.4
Configuration: /var/www/phpunit.xml

Testing Drupal\Tests\hr_paragraphs\ExistingSite\HrParagraphsRWAssessmentsTest
....                                                                4 / 4 (100%)

Time: 00:09.048, Memory: 92.50 MB

OK (4 tests, 11 assertions)

HTML output was generated
http://hrinfo-site.docksal.site/sites/simpletest/browser_output/Drupal_Tests_hr_paragraphs_ExistingSite_HrParagraphsRWAssessmentsTest-139-dtt.html
http://hrinfo-site.docksal.site/sites/simpletest/browser_output/Drupal_Tests_hr_paragraphs_ExistingSite_HrParagraphsRWAssessmentsTest-140-dtt.html
http://hrinfo-site.docksal.site/sites/simpletest/browser_output/Drupal_Tests_hr_paragraphs_ExistingSite_HrParagraphsRWAssessmentsTest-141-dtt.html
http://hrinfo-site.docksal.site/sites/simpletest/browser_output/Drupal_Tests_hr_paragraphs_ExistingSite_HrParagraphsRWAssessmentsTest-142-dtt.html
http://hrinfo-site.docksal.site/sites/simpletest/browser_output/Drupal_Tests_hr_paragraphs_ExistingSite_HrParagraphsRWAssessmentsTest-143-dtt.html

```

**Comment by attiks** [comment]
@lazysoundsystem can you run the test locally to help debug?

**Comment by lazysoundsystem** [comment]
Sorry it took a while - I've managed to run that test locally and no errors, and following the steps of the test manually, I end up on example.com with no mention of the word 'Assessments'.

I do see this comment in the test function `renderGroupTabRedirect()`:
```
    // Disable the rule, throws an error on line 184 in
    // html/core/modules/path_alias/src/AliasManager.php.
    $theme_rule->disable()->save();
```
https://github.com/UN-OCHA/response-site/blob/develop/html/modules/custom/hr_paragraphs/tests/src/ExistingSite/HrParagraphsRWAssessmentsTest.php - line 211

Not sure if that could be related?

**Comment by attiks** [comment]
Not really, that code is "old", and changes in this file are not even close to the failing code

**Comment by attiks** [comment]
Test disabled and marked as todo

**Comment by attiks** [comment]
Build is failing on missing slack channel 😭

**Pull request merged**
