### PR TITLE
bug: Do not remove content

### PR DESCRIPTION
**Pull request by attiks**
Refs: #RWR-264

### CODE REVIEW

**Review by left23 — APPROVED** [review]
I'm too in the middle of a PR to test this easily so I'm approving without testing.

The JS seems to be quite different from the RW implementation (in code, not the end result). Was this due to differences in content model?
https://github.com/UN-OCHA/rwint9-site/blob/develop/html/themes/custom/common_design_subtheme/components/rw-toc/rw-toc.js

**Comment by attiks** [comment]
You have to ask @rupl he added ot

**Comment by left23** [comment]
I tested this on Dev. 
There is no ToC when I add only one item, as intended, and it displays as it should when there are two items.

**Comment by left23** [comment]
> You have to ask @rupl he added it

My mistake, I'm getting confused between the RW ToC and CD/RWR ToC. This isn't the implementation of RW ToC so it's not comparable.

**Pull request merged**
