### PR TITLE
[RWR-185] Table of Contents paragraph

### PR DESCRIPTION
**Pull request by rupl**
# RWR-185

First pass at a Table of Contents. It's built client-side from the Paragraphs markup in the main column coming from `field_paragraphs`. It's only available on Operations and Cluster/WG entities (i.e  NOT on Pages, Landing Pages, or any other "sub-page" of an Operation or C/WG). The ToC can be placed like a normal Paragraph inside the Sidebar.

Like any other paragraph inside the Sidebar, it will be carried over to a sub-Page automatically. I don't know yet if that makes sense, but since it's built client-side it will always reflect the page's contents accurately.

It scans the page for `.field--name-field-title` and adds to the list of links only when that selector is found inside a given Paragraph.

There's smooth scrolling but if the user prefers reduced motion in their global browser settings, the links snap directly to their location old-school style.

### CODE REVIEW

**Comment by lazysoundsystem** [comment]
From https://app.travis-ci.com/github/UN-OCHA/response-site/builds/254291748
```
There was 1 error:

1) Drupal\Tests\hr_paragraphs\ExistingSite\HrParagraphsOperationTabTitlesTest::testOperationTabTitles

Behat\Mink\Exception\ExpectationException: No title element found on the page
```

**Comment by rupl** [comment]
I find that odd given the change that caused it. I tried re-running the build from both GitHub UI and Travis UI, neither worked so I force pushed to the original offending commit fe1e431...f02ec59 — hopefully Travis changes his mind!

**Comment by rupl** [comment]
🎉 bazinga! 🎉

**Review by lazysoundsystem — APPROVED** [review]
Tested locally and all works as expected from the description

**Comment by rupl** [comment]
I did yet another round of testing myself and realized I'd missed several config settings. Namely, it wasn't excluded in enough places, and when the optional Title/Text fields were filled in, it was showing undesireable field labels.

**Pull request merged**
