### PR TITLE
20230801 d10

### PR DESCRIPTION
**Pull request by attiks**
Replaces https://github.com/UN-OCHA/response-site/pull/543

### CODE REVIEW

**Review by lazysoundsystem — APPROVED** [review]
Just set this up locally and all very smooth and easy.

Just one thing to watch during deployment:
I got a message during `drush cim`: 'block' entity with ID 'claro_help' already exists. I needed to run `cim` twice to import all the config.

Doesn't need to be in this PR, but we ought to move to CKEditor5 as CKEditor4 is EOL this year - were there issues you came across in changing to it in the other PR? There's already a ticket for that: https://humanitarian.atlassian.net/browse/OPS-9268, so it can be handled separately from the D10 upgrade.

Related - looks like Seven is removed here, presumably it's added in composer.json to make the switch easier and should be removed from that in a follow-up task.

**Comment by attiks** [comment]
> I got a message during drush cim: 'block' entity with ID 'claro_help' already exists. I needed to run cim twice to import all the config.

Strange, let's see what dev will do

Might be easier to do CKEditor 5 and seven after prod deployment

Let's see if @rupl has opinions

**Comment by rupl** [comment]
No opinions, happy to defer the upgrades for now. If there are dupe blocks I wasn't actively using the Claro help, so feel free to delete if it causes trouble.

**Comment by attiks** [comment]
See https://github.com/UN-OCHA/response-site/pull/614

**Pull request closed without merging**
