### PR TITLE
chore: add and configure config_split

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-7850

Adding the line in the README to settings.local.php turns on and configures dblog, views_ui, stage_file_proxy and devel.

(Realized https://github.com/UN-OCHA/response-site/pull/523 was based on an older branch and had conflicts. Use this one instead.)

### CODE REVIEW

**Review by attiks — APPROVED** [review]

**Review by rupl — APPROVED** [review]
My one minor nit is that reliefweb.int is only a sensible SFP default for one website. But in general this came on a good day for me, I needed it! Merging :shipit:

**Comment by rupl** [comment]
@lazysoundsystem I updated the config in my current branch. Thanks again!

**Comment by lazysoundsystem** [comment]
Thanks Chris - I copied all the config_dev files direct from RWint and forgot to change the domain for this site - I'll make another PR for that.

**Comment by lazysoundsystem** [comment]
@rupl and then I followed the link and saw you'd already done that...

**Comment by rupl** [comment]
When I made the comment I had in my mind that we needed to change something "upstream" somewhere, but that's not the case. Either way, your setup is working great on my local and this repo now has the expected SFP origin when someone enabled config split  👍

**Pull request merged**
